### ISSUE TITLE
Dataset Request 

### ISSUE THREAD

**Issue by avran-v** [chenhaoxing/DeMamba#2]
Hi, we are currently conducting research on AI-generated content detection and we are interested in utilizing your GenVideo dataset. Is it possible for us to obtain access to it?

**Comment by chenhaoxing** [comment]
> Hi, we are currently conducting research on AI-generated content detection and we are interested in utilizing your GenVideo dataset. Is it possible for us to obtain access to it?

Hello, we have recently made some progress in advancing the open source process. We hope to open source in the next two weeks.

**Comment by avran-v** [comment]
I am looking to download the test set. I am able to download the real videos (GenVideo-Val.zip), how can I download the generated videos from the test set?

**Comment by chenhaoxing** [comment]
Hi, the Val.zip file is the test set in our paper.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Keerthi V ***@***.***>
发送时间: Thursday, July 25, 2024 11:53:22 PM
收件人: chenhaoxing/DeMamba ***@***.***>
抄送: chx_ant ***@***.***>; Comment ***@***.***>
主题: Re: [chenhaoxing/DeMamba] Dataset Request (Issue #2)


I am looking to download the test set. I am able to download the real videos (GenVideo-Val.zip), how can I download the generated videos from the test set?

―

**Comment by Franklin-Jiang** [comment]
I noticed that most of the data set files published at [ModelScope](https://modelscope.cn/datasets/cccnju/Gen-Video/files) use the file name of xxx.split.aa. What is the format of these files? How should we decompress and use the data?
