### ISSUE TITLE
Requirest for pre-trained model

### ISSUE THREAD

**Issue by TRISKEL10N** [chenhaoxing/DeMamba#5]
Thank you for your amazing method！
We plan to research AI-generated content detection, however, we have found that only the encoder part of the model is provided in this code.
If you can provide complete pre-trained models for different encoders? We would greatly appreciate it!

**Comment by chenhaoxing** [comment]
Hello. Apologies, but due to the company's management policies, we are unable to provide pre-trained models at the moment.

**Comment by TRISKEL10N** [comment]
Thank you for your patience and responses! We have noticed the updated dataset and will attempt to train the model with your code.
